name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare data
      run: |
        python src/data_preparation.py

    - name: Run tests
      run: pytest tests/

    - name: Build Docker image
      run: docker build -t time_series_forecast
       .

    - name: Push Docker image (optional)
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin
        docker tag my_ml_project $DOCKER_USERNAME/my_ml_project:latest
        docker push $DOCKER_USERNAME/my_ml_project:latest

